sudo: required
service:
  - dockerfile

before_install:
  - docker build -t nishabosch/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nishabosch/docker-react npm run test -- --coverage